"""Constants for the Wiser Home integration."""

DOMAIN = "wiser_home"
DEFAULT_NAME = "Wiser Home"
DEFAULT_TOLERANCE = 0.3
OFF_VALUE = "OFF"
SCHEDULE_INTERVAL = 1

CONF_AT_STARTUP = "reset_at_startup"
CONF_BOILER = "boiler"
CONF_DAYS = "days"
CONF_END = "end"
CONF_END_DATE = "end_date"
CONF_EVENTS = "expressions_from_events"
CONF_EXPR = "expression"
CONF_EXPR_ENV = "expression_environment"
CONF_MONTHS = "months"
CONF_ROOMS = "rooms"
CONF_RULES = "rules"
CONF_SCHEDULE = "schedule"
CONF_SCH_APPEND = "schedule_append"
CONF_SCH_PREPEND = "schedule_prepend"
CONF_SCH_SNIPPETS = "schedule_snippets"
CONF_START = "start"
CONF_START_DATE = "start_date"
CONF_THERM = "thermostat"
CONF_VALUE = "value"
CONF_WEEKDAYS = "weekdays"
CONF_WEEKS = "weeks"
CONF_YEARS = "years"
CONF_WEIGHT = "weight"

