set_away_mode:
  description: Sets the system to Away Mode
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'sensor.wiser_home'
    away_mode:
      description: Activate/desactivate (true/false) the away mode.
      example: true
set_away_temp:
  description: Set the Away Mode temperature.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'sensor.wiser_home'
    temperature:
      description: The new target temperature for the Wiser Home.
      example: 25